name: storeus_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.8
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0

dev_dependencies:
  analyzer: null
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter:
  uses-material-design: true
